addSbtPlugin("com.codecommit"            % "sbt-github-actions"            % "0.13.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"                % "1.5.7")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.4.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"                 % "1.8.2")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                       % "0.4.3")
